### ISSUE TITLE
Mac Work

### ISSUE THREAD

**Issue by joshuanknight** [wolfgangasdf/gmail-attachment-remover#1]
Hello, I'm trying to get this to work on Mac OS Monterey.  I was able to download the App, put it into my Applications directory, and get it to start by ChMod (https://www.howtogeek.com/682509/mac-app-not-starting-heres-how-to-fix-it/), however, the application icon comes up, and the 'gar' icon appears on my toolbar, but nothing actually opens.  Please help.  Thanks, Joshua

**Comment by wolfgangasdf** [comment]
Hi, sorry, I currently can't test on monterey, I have uploaded updated java 18 versions, probably this works. Otherwise, see the change in the README file (about https://github.com/ilovefreesw/unattach), or can you post the output of running it manually from terminal.app from the folder where you placed the app via `./GmailAttachmentRemover.app/Contents/MacOS/GmailAttachmentRemover` ?

**Comment by joshuanknight** [comment]
Thanks, Wolfgang.  Note, I’m a novice. Perhaps I’m missing something basic? I reinstalled your App from the website.  I haven’t installed any Java.  Should I have?  Here’s what I get from Terminal:

/Applications/GmailAttachmentRemover.app/Contents/MacOS/GmailAttachmentRemover: line 156: /Applications/GmailAttachmentRemover.app/Contents/bin/java: Permission denied
/Applications/GmailAttachmentRemover.app/Contents/MacOS/GmailAttachmentRemover: line 156: exec: /Applications/GmailAttachmentRemover.app/Contents/bin/java: cannot execute: Undefined error: 0
***@***.*** ~ % 

Thanks, Joshua
Joshua Knight | Program Engineer | Global Hope Network International
+1 (303) 919-2872 | ghni.org <http://ghni.org/> 
Schedule a call with me: calendly.com/joshua-knight <http://calendly.com/joshua-knight> 
Support our work: https://www.globalhopenetwork.org/about/staff/joshua-knight <https://www.globalhopenetwork.org/about/staff/joshua-knight> 
Zoom Meeting: https://regis.zoom.us/j/9991460763 <https://regis.zoom.us/j/9991460763>

**Comment by wolfgangasdf** [comment]
Hi, it seems that the apple "Archive Utility.app" looses permissions of gradle-produced zips. I haven't seen it in ages since I use https://theunarchiver.com/ . Or, solved by (the link from you didn't know about /bin):

```
chmod +x GmailAttachmentRemover.app/Contents/bin/*
chmod +x GmailAttachmentRemover.app/Contents/MacOS/*
```
In any case, no need to put it into /Applications.

**Comment by joshuanknight** [comment]
It worked, Wolfgang! Sort of! It opened now, but when I click on the “Gmail Account” dropdown, nothing happens.  Thoughts?  Here is the Terminal output below.  Thanks! Joshua

Last login: Sat Apr 30 15:32:14 on ttys000
***@***.*** ~ % chmod +x GmailAttachmentRemover.app/Contents/bin/*
chmod +x GmailAttachmentRemover.app/Contents/MacOS/*
zsh: no matches found: GmailAttachmentRemover.app/Contents/bin/*
zsh: no matches found: GmailAttachmentRemover.app/Contents/MacOS/*
***@***.*** ~ % ./GmailAttachmentRemover.app/Contents/MacOS/GmailAttachmentRemover
zsh: no such file or directory: ./GmailAttachmentRemover.app/Contents/MacOS/GmailAttachmentRemover
***@***.*** ~ % chmod +x GmailAttachmentRemover.app/Contents/bin/*
chmod +x GmailAttachmentRemover.app/Contents/MacOS/*
zsh: no matches found: GmailAttachmentRemover.app/Contents/bin/*
zsh: no matches found: GmailAttachmentRemover.app/Contents/MacOS/*
***@***.*** ~ % chmod +x GmailAttachmentRemover.app/Contents/bin/*
zsh: no matches found: GmailAttachmentRemover.app/Contents/bin/*
***@***.*** ~ % cd Downloads
***@***.*** Downloads % chmod +x GmailAttachmentRemover.app/Contents/bin/*
***@***.*** Downloads % chmod +x GmailAttachmentRemover.app/Contents/MacOS/*
***@***.*** Downloads % ./GmailAttachmentRemover.app/Contents/MacOS/GmailAttachmentRemover
May 02, 2022 8:17:01 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3197c20f'
Prism pipeline init order: sw 
Using Double Precision Marlin Rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
*** Fallback to Prism SW pipeline
Prism pipeline name = com.sun.prism.sw.SWPipeline
(X) Got class = class com.sun.prism.sw.SWPipeline
Initialized prism pipeline: com.sun.prism.sw.SWPipeline
 vsync: true vpipe: false
SGAR build time: Fri Feb 01 00:00:00 MST 1980
load config: settings file = /Users/joshuaknight/Library/Application Support/Sgar/sgarsettings.txt
Logging to file /tmp/sgar-1651544222356.txt
caffeinate (false)...
QuantumRenderer: shutdown
***@***.*** Downloads % ./GmailAttachmentRemover.app/Contents/MacOS/GmailAttachmentRemover

May 03, 2022 8:57:43 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3197c20f'
Prism pipeline init order: sw 
Using Double Precision Marlin Rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
*** Fallback to Prism SW pipeline
Prism pipeline name = com.sun.prism.sw.SWPipeline
(X) Got class = class com.sun.prism.sw.SWPipeline
Initialized prism pipeline: com.sun.prism.sw.SWPipeline
 vsync: true vpipe: false
SGAR build time: Fri Feb 01 00:00:00 MST 1980
load config: settings file = /Users/joshuaknight/Library/Application Support/Sgar/sgarsettings.txt
Logging to file /tmp/sgar-1651589863643.txt

And log from GAR:
============= Application log ==================== 
SGAR build time: Fri Feb 01 00:00:00 MST 1980
load config: settings file = /Users/joshuaknight/Library/Application Support/Sgar/sgarsettings.txt
Logging to file /tmp/sgar-1651589863643.txt

**Comment by joshuanknight** [comment]
Sorry, Wolfgang, I'm still hoping to get this to work, but perhaps I should
get teh paid version? Thank,s Joshua

*------------------------------*
*Joshua Knight *| Program Engineer |
*Global Hope Network International*+1-303-919-2872 | ghni.org
Schedule a call with me: calendly.com/joshua-knight
Support our work:
https://www.globalhopenetwork.org/about/staff/joshua-knight

**Comment by wolfgangasdf** [comment]
Hi, how about clicking "add" to add a gmail account? will add to README in future.

**Comment by joshuanknight** [comment]
Ha! I can't believe I missed tha!
OK, I loaded my gmail account.
When I clicked the 'Get app password' button, it took me into Gmail to get
my password, but it said something's broken after I signed in.  Perhaps
that section isn't working anymore?  I went ahead and just typed my
password in the box to the loft of 'Get my password'.
I then clicked 'Find emails', but it crashed again, as seen in the below
paste from Terminal.
Is there something additional for me to do?
Thank you so much for your patience and persistence!
Peace, Joshua

***@***.*** downloads %
./GmailAttachmentRemover.app/Contents/MacOS/GmailAttachmentRemover

Oct 11, 2022 6:58:15 PM com.sun.javafx.application.PlatformImpl startup

WARNING: Unsupported JavaFX configuration: classes were loaded from
'unnamed module @35906287'

Prism pipeline init order: sw

Using Double Precision Marlin Rasterizer

Using dirty region optimizations

Not using texture mask for primitives

Not forcing power of 2 sizes for textures

Using hardware CLAMP_TO_ZERO mode

Opting in for HiDPI pixel scaling

*** Fallback to Prism SW pipeline

Prism pipeline name = com.sun.prism.sw.SWPipeline

(X) Got class = class com.sun.prism.sw.SWPipeline

Initialized prism pipeline: com.sun.prism.sw.SWPipeline

 vsync: true vpipe: false

SGAR build time: Fri Feb 01 00:00:00 MST 1980

load config: settings file = /Users/joshuaknight/Library/Application
Support/Sgar/sgarsettings.txt

Logging to file /tmp/sgar-1665536295527.txt

caffeinate (true)...

Exception in thread "JavaFX Application Thread" java.io.IOException: Cannot
run program "/usr/bin/caffeinate": error=93, Attribute not found

at java.base/java.lang.ProcessBuilder.start(Unknown Source)

at java.base/java.lang.ProcessBuilder.start(Unknown Source)

at sgar.Helpers$.caffeinate(Sgar.scala:598)

at sgar.Sgar$$anon$36.$anonfun$new$16(Sgar.scala:417)

at sgar.Sgar$$anon$36.$anonfun$new$16$adapted(Sgar.scala:389)

at scalafx.event.EventIncludes$$anon$6.handle(EventIncludes.scala:167)

at
com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)

at
com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)

at
com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)

at
com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)

at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)

at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)

at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)

at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)

at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)

at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)

at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)

at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)

at javafx.event.Event.fireEvent(Event.java:198)

at javafx.scene.Node.fireEvent(Node.java:8797)

at javafx.scene.control.Button.fire(Button.java:203)

at
com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)

at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)

at
com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)

at
com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)

at
com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)

at
com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)

at
com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)

at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)

at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)

at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)

at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)

at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)

at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)

at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)

at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)

at javafx.event.Event.fireEvent(Event.java:198)

at javafx.scene.Scene$MouseHandler.process(Scene.java:3881)

at javafx.scene.Scene.processMouseEvent(Scene.java:1874)

at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)

at
com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)

at
com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)

at java.base/java.security.AccessController.doPrivileged(Unknown Source)

at
com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)

at
com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)

at
com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)

at com.sun.glass.ui.View.handleMouseEvent(View.java:551)

at com.sun.glass.ui.View.notifyMouse(View.java:937)

at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)

Caused by: java.io.IOException: error=93, Attribute not found

at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)

at java.base/java.lang.ProcessImpl.<init>(Unknown Source)

at java.base/java.lang.ProcessImpl.start(Unknown Source)

... 49 more

XXX: ***@***.***

xx=[SFX]BoundingBox [minX:301.0, minY:158.0, minZ:0.0, width:78.5,
height:26.0, depth:0.0, maxX:379.5, maxY:184.0, maxZ:0.0] t=Find emails
based on selected criteria

xx=[SFX]BoundingBox [minX:383.5, minY:158.0, minZ:0.0, width:133.0,
height:26.0, depth:0.0, maxX:516.5, maxY:184.0, maxZ:0.0] t=Remove all
attachments shown in the table below

xx=[SFX]BoundingBox [minX:8.0, minY:549.5, minZ:0.0, width:140.0,
height:26.0, depth:0.0, maxX:148.0, maxY:575.5, maxZ:0.0] t=... to prevent
attachments from being removed

xx=[SFX]BoundingBox [minX:520.5, minY:158.0, minZ:0.0, width:121.0,
height:26.0, depth:0.0, maxX:641.5, maxY:184.0, maxZ:0.0] t=Mainly for
debug purposes. Output is shown in log.

xx=[SFX]BoundingBox [minX:645.5, minY:158.0, minZ:0.0, width:50.5,
height:26.0, depth:0.0, maxX:696.0, maxY:184.0, maxZ:0.0] t=Open website
https://github.com/wolfgangasdf/gmail-attachment-remover

xx=[SFX]BoundingBox [minX:97.5, minY:8.0, minZ:0.0, width:520.0,
height:26.0, depth:0.0, maxX:617.5, maxY:34.0, maxZ:0.0] t=Gmail email
adress

xx=[SFX]BoundingBox [minX:88.5, minY:98.0, minZ:0.0, width:903.5,
height:26.0, depth:0.0, maxX:992.0, maxY:124.0, maxZ:0.0] t=mind that '
label:<label>' is appended!

xx=[SFX]BoundingBox [minX:77.5, minY:68.0, minZ:0.0, width:914.5,
height:26.0, depth:0.0, maxX:992.0, maxY:94.0, maxZ:0.0] t=Only consider
emails having this label; consider all if empty

save config: settings file = /Users/joshuaknight/Library/Application
Support/Sgar/sgarsettings.txt

caffeinate (false)...

***@***.*** downloads %

*------------------------------*
*Joshua Knight *| Program Engineer |
*Global Hope Network International*+1-303-919-2872 | ghni.org
Schedule a call with me: calendly.com/joshua-knight
Support our work:
https://www.globalhopenetwork.org/about/staff/joshua-knight

**Comment by wolfgangasdf** [comment]
No idea why caffeinate (mac sleep prevention) doesn't work for you - I have uploaded a new release where this is disabled by default. The error above should disappear, let's see what comes next :)

**Comment by joshuanknight** [comment]
Hello, Wolfgang,
I looked for your releases here:
https://github.com/wolfgangasdf/gmail-attachment-remover/releases.
But it was empty.  Please correct me on where to find the latest release.
Thanks, Joshua

*------------------------------*
*Joshua Knight *| Program Engineer |
*Global Hope Network International*+1-303-919-2872 | ghni.org
Schedule a call with me: calendly.com/joshua-knight
Support our work:
https://www.globalhopenetwork.org/about/staff/joshua-knight

**Comment by wolfgangasdf** [comment]
Forgot to reply, caffeinate (preventing computer from sleep) is now disabled by default.
