### ISSUE TITLE
"Get app password" button doesn't work

### ISSUE THREAD

**Issue by michalfapso** [wolfgangasdf/gmail-attachment-remover#5]
I'm on Ubuntu 22.04.4. Clicking on the button doesn't even show any error in the terminal. Looking at the source code it should just open the url:
https://security.google.com/settings/security/apppasswords

So I just opened it manually in my browser. Everything else worked properly.

Thanks for this project!

**Comment by wolfgangasdf** [comment]
Thanks - should be fixed with 2ba0abb !
